services:
  # MySQL
  mysql-test:
    image: mysql:8
    container_name: mysql-test
    ports:
      - "3308:3306"  # External port 3308, internal port 3306
    environment:
      MYSQL_ROOT_PASSWORD: testing
      MYSQL_DATABASE: mscv_information_test
    networks:
      - networking-test
    volumes:
      - vmTestSql:/var/lib/mysql  # Named volume
    restart: on-failure

  # Keycloak
  keycloak:
    container_name: keycloak-test
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    ports:
      - "8181:8181"  # External port 8181, internal port 8181
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: uncledave
      DB_PASSWORD: Test123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181
    networks:
      - networking-test
    volumes:
      - "C:/Users/GAMER/Pictures/MICRO-PROJEC2/Storage Keycloak:/opt/keycloak/data"
    restart: on-failure

  # Config Server
  server-configuration:
    image: joshua76i/config-server-pr2:latest
    container_name: config-container-test
    ports:
      - "8888:8888"  # External port 8888, internal port 8888
    networks:
      - networking-test
    restart: on-failure

  # Redis
  redis-test:
    image: redis:alpine3.20
    container_name: redis-server-test
    restart: on-failure
    ports:
      - "6380:6379"  # External port 6379, internal port 6379
    command: redis-server --loglevel warning --requirepass testingRedis
    networks:
      - networking-test
    volumes:
      - redis-data-test:/data  # Custom volume name

networks:
  networking-test:
    driver: bridge

volumes:
  vmTestSql: {}    # Named volume for MySQL
  redis-data-test: {}  # Named volume for Redis
