spring.application.name=web-page
server.port=${SERVER_PORT:8903}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

# Redis Configuration
svc.redis.host=${REDIS_HOST:redis}
svc.redis.port=${REDIS_PORT:6379}   
svc.redis.password=${REDIS_PASS}
svc.kafka.bootstrapAddress=${KAFKA_HOST:kafka:9092}

svc.info.name=${SERVER_INF_NAME:server-information}
svc.info.port=${SERVER_INF_PORT:8111}
svc.info.url=${SERVER_INF_URL:lb://server-information}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://keycloak:8181/realms/docker-real}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_URI:http://keycloak:8181/realms/docker-real/protocol/openid-connect/certs}
jwt.auth.converter.resource-id=${JWT_RESOURCE_ID:Docker-Gym}
jwt.auth.converter.principle-attribute=${JWT_PRINCIPAL_ATTR:preferred_username}

spring.cloud.kubernetes.secrets.enable-api=true
spring.cloud.kubernetes.discovery.all-namespaces=true 
spring.profiles.active=dev
management.endpoint.gateway.enabled=true
management.endpoints.web.exposure.include=health,info,auditevents

management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
spring.cloud.kubernetes.config.enabled=true