spring.application.name=web-page
server.port=8903

# Redis Configuration
svc.redis.host=localhost
svc.redis.port=6379
svc.redis.password=test-redis-password
svc.kafka.bootstrapAddress=localhost:29092

svc.info.name=server-information
svc.info.port=8111
svc.info.url=lb://server-information

management.endpoint.gateway.enabled=true
management.endpoints.web.exposure.include=health,info,auditevents
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
